-- =====================================================================
-- 00_setup.sql  -  run ONCE in a Snowsight SQL worksheet as ACCOUNTADMIN
-- Creates: warehouse, database, 4 schemas, 2 roles, 1 service user.
-- =====================================================================
USE ROLE ACCOUNTADMIN;

-- 1. Compute. X-SMALL + AUTO_SUSPEND=60 keeps the free-trial credits safe.
CREATE WAREHOUSE IF NOT EXISTS SETTLE_WH
  WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- 2. Storage: one database, one schema per medallion layer + AUDIT.
CREATE DATABASE IF NOT EXISTS SETTLEMENT_DB;
CREATE SCHEMA IF NOT EXISTS SETTLEMENT_DB.BRONZE;   -- raw, as received
CREATE SCHEMA IF NOT EXISTS SETTLEMENT_DB.SILVER;   -- validated + typed
CREATE SCHEMA IF NOT EXISTS SETTLEMENT_DB.GOLD;     -- star schema + KPIs
CREATE SCHEMA IF NOT EXISTS SETTLEMENT_DB.AUDIT;    -- DQ log, watermarks, run log

-- 3. Roles (least privilege):
--    PIPELINE_ROLE  builds and writes every layer
--    API_ROLE       can only READ the GOLD layer
CREATE ROLE IF NOT EXISTS PIPELINE_ROLE;
CREATE ROLE IF NOT EXISTS API_ROLE;
GRANT ROLE PIPELINE_ROLE TO ROLE SYSADMIN;   -- so you (ACCOUNTADMIN/SYSADMIN) can see the tables
GRANT ROLE API_ROLE      TO ROLE SYSADMIN;

GRANT USAGE ON WAREHOUSE SETTLE_WH     TO ROLE PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE SETTLE_WH     TO ROLE API_ROLE;
GRANT USAGE ON DATABASE SETTLEMENT_DB  TO ROLE PIPELINE_ROLE;
GRANT USAGE ON DATABASE SETTLEMENT_DB  TO ROLE API_ROLE;

GRANT ALL ON SCHEMA SETTLEMENT_DB.BRONZE TO ROLE PIPELINE_ROLE;
GRANT ALL ON SCHEMA SETTLEMENT_DB.SILVER TO ROLE PIPELINE_ROLE;
GRANT ALL ON SCHEMA SETTLEMENT_DB.GOLD   TO ROLE PIPELINE_ROLE;
GRANT ALL ON SCHEMA SETTLEMENT_DB.AUDIT  TO ROLE PIPELINE_ROLE;

GRANT USAGE ON SCHEMA SETTLEMENT_DB.GOLD TO ROLE API_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SETTLEMENT_DB.GOLD TO ROLE API_ROLE;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA SETTLEMENT_DB.GOLD TO ROLE API_ROLE;

-- 4. Service user that logs in with a key pair (no password).
--    Paste the contents of keys/rsa_key.pub WITHOUT the
--    "-----BEGIN PUBLIC KEY-----" / "-----END PUBLIC KEY-----" lines, all on one line.
CREATE USER IF NOT EXISTS SETTLE_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = PIPELINE_ROLE
  DEFAULT_WAREHOUSE = SETTLE_WH
  RSA_PUBLIC_KEY = 'PASTE_YOUR_PUBLIC_KEY_HERE';

GRANT ROLE PIPELINE_ROLE TO USER SETTLE_SVC;
GRANT ROLE API_ROLE      TO USER SETTLE_SVC;

-- Check: the user should show RSA_PUBLIC_KEY_FP filled in.
DESC USER SETTLE_SVC;
