-- =====================================================================
-- 01_bronze_audit_ddl.sql   (run by: python -m pipeline.run_pipeline --init)
-- BRONZE = data exactly as received. Every column is text and nothing is
-- rejected here, so history can always be replayed.
-- =====================================================================

CREATE FILE FORMAT IF NOT EXISTS BRONZE.CSV_FMT
  TYPE = CSV SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"' EMPTY_FIELD_AS_NULL = TRUE;

-- Stage = a folder inside Snowflake where we upload the CSV files.
CREATE STAGE IF NOT EXISTS BRONZE.RAW_STAGE FILE_FORMAT = BRONZE.CSV_FMT;

CREATE TABLE IF NOT EXISTS BRONZE.MERCHANT (
  MERCHANT_ID VARCHAR, MERCHANT_NAME VARCHAR, MERCHANT_CATEGORY VARCHAR, COUNTRY VARCHAR,
  RISK_LEVEL VARCHAR, EFFECTIVE_FROM VARCHAR, EFFECTIVE_TO VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.TRANSACTIONS (
  TRANSACTION_ID VARCHAR, MERCHANT_ID VARCHAR, CUSTOMER_ID VARCHAR, TRANSACTION_TS VARCHAR,
  AMOUNT VARCHAR, CURRENCY VARCHAR, STATUS VARCHAR, PAYMENT_CHANNEL VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.SETTLEMENTS (
  SETTLEMENT_ID VARCHAR, TRANSACTION_ID VARCHAR, SETTLEMENT_TS VARCHAR, SETTLEMENT_AMOUNT VARCHAR,
  SETTLEMENT_STATUS VARCHAR, SETTLEMENT_BATCH VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.PAYMENT_EVENTS (
  EVENT_ID VARCHAR, TRANSACTION_ID VARCHAR, EVENT_TYPE VARCHAR, EVENT_TS VARCHAR,
  INGESTION_TS VARCHAR, PROCESSING_MS VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------
-- AUDIT schema
-- ---------------------------------------------------------------------

-- Invalid records never disappear: every rejected / quarantined / warning row lands here.
CREATE TABLE IF NOT EXISTS AUDIT.DQ_LOG (
  RUN_ID      VARCHAR NOT NULL,
  SOURCE      VARCHAR NOT NULL,          -- transactions / settlements / ...
  RECORD_KEY  VARCHAR,                   -- id of the bad record (if it had one)
  SEVERITY    VARCHAR NOT NULL,          -- REJECT / QUARANTINE / WARNING
  REASON      VARCHAR NOT NULL,          -- e.g. MISSING_MERCHANT_ID
  RAW_RECORD  VARCHAR,                   -- original row as JSON (customer id masked)
  LOGGED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Incremental processing: "up to which load time did we already process?"
CREATE TABLE IF NOT EXISTS AUDIT.WATERMARK (
  SOURCE        VARCHAR NOT NULL PRIMARY KEY,   -- merchant / transactions / settlements / payment_events / gold
  LAST_LOAD_TS  TIMESTAMP_LTZ NOT NULL
);

INSERT INTO AUDIT.WATERMARK (SOURCE, LAST_LOAD_TS)
SELECT column1, '1970-01-01'::TIMESTAMP_LTZ
FROM VALUES ('merchant'), ('transactions'), ('settlements'), ('payment_events'), ('gold')
WHERE column1 NOT IN (SELECT SOURCE FROM AUDIT.WATERMARK);

-- Monitoring: one row per pipeline run.
CREATE TABLE IF NOT EXISTS AUDIT.PIPELINE_RUNS (
  RUN_ID            VARCHAR NOT NULL PRIMARY KEY,
  STARTED_AT        TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  FINISHED_AT       TIMESTAMP_LTZ,
  STATUS            VARCHAR,             -- RUNNING / SUCCESS / FAILED
  FILES_LOADED      NUMBER,
  ROWS_LOADED       NUMBER,
  ROWS_QUARANTINED  NUMBER,
  ROWS_REJECTED     NUMBER,
  ERROR_MESSAGE     VARCHAR
);
