-- =====================================================================
-- 01_bronze_audit_ddl.sql   (run by: python -m pipeline.run_pipeline --init)
-- BRONZE = data exactly as received. Every column is text, nothing is
-- rejected here, so we can always replay history.
-- =====================================================================

CREATE FILE FORMAT IF NOT EXISTS BRONZE.CSV_FMT
  TYPE = CSV
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  EMPTY_FIELD_AS_NULL = TRUE;

-- Internal stage = a landing folder inside Snowflake for our CSV files.
CREATE STAGE IF NOT EXISTS BRONZE.RAW_STAGE FILE_FORMAT = BRONZE.CSV_FMT;

CREATE TABLE IF NOT EXISTS BRONZE.MERCHANT (
  MERCHANT_ID VARCHAR, MERCHANT_NAME VARCHAR, MERCHANT_CATEGORY VARCHAR, COUNTRY VARCHAR,
  RISK_LEVEL VARCHAR, EFFECTIVE_FROM VARCHAR, EFFECTIVE_TO VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.TRANSACTIONS (
  TRANSACTION_ID VARCHAR, MERCHANT_ID VARCHAR, CUSTOMER_ID VARCHAR, TRANSACTION_TS VARCHAR,
  AMOUNT VARCHAR, CURRENCY VARCHAR, STATUS VARCHAR, PAYMENT_CHANNEL VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.SETTLEMENTS (
  SETTLEMENT_ID VARCHAR, TRANSACTION_ID VARCHAR, SETTLEMENT_TS VARCHAR, SETTLEMENT_AMOUNT VARCHAR,
  SETTLEMENT_STATUS VARCHAR, SETTLEMENT_BATCH VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS BRONZE.PAYMENT_EVENTS (
  EVENT_ID VARCHAR, TRANSACTION_ID VARCHAR, EVENT_TYPE VARCHAR, EVENT_TS VARCHAR,
  INGESTION_TS VARCHAR, PROCESSING_MS VARCHAR,
  SOURCE_FILE VARCHAR, LOAD_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ---------------------------------------------------------------------
-- AUDIT: makes sure invalid records never silently disappear.
-- ---------------------------------------------------------------------

-- Every rejected / quarantined / warning record, with the reason.
CREATE TABLE IF NOT EXISTS AUDIT.DQ_LOG (
  RUN_ID      VARCHAR NOT NULL,
  SOURCE      VARCHAR NOT NULL,          -- transactions / settlements / ...
  RECORD_KEY  VARCHAR,                   -- the record's id (if it had one)
  SEVERITY    VARCHAR NOT NULL,          -- REJECT / QUARANTINE / WARNING
  REASON      VARCHAR NOT NULL,          -- e.g. MISSING_MERCHANT_ID
  RAW_RECORD  VARCHAR,                   -- original row as JSON (customer_id masked)
  LOGGED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

-- Incremental processing: "how far did each layer get last time?"
CREATE TABLE IF NOT EXISTS AUDIT.WATERMARK (
  LAYER        VARCHAR NOT NULL,
  SOURCE       VARCHAR NOT NULL,
  LAST_LOAD_TS TIMESTAMP_LTZ NOT NULL,
  UPDATED_AT   TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_WATERMARK PRIMARY KEY (LAYER, SOURCE)
);

MERGE INTO AUDIT.WATERMARK w
USING (SELECT column1 AS LAYER, column2 AS SOURCE FROM VALUES
         ('SILVER', 'merchant'), ('SILVER', 'transactions'),
         ('SILVER', 'settlements'), ('SILVER', 'payment_events'), ('GOLD', 'ALL')) s
ON w.LAYER = s.LAYER AND w.SOURCE = s.SOURCE
WHEN NOT MATCHED THEN INSERT (LAYER, SOURCE, LAST_LOAD_TS)
  VALUES (s.LAYER, s.SOURCE, '1970-01-01 00:00:00'::TIMESTAMP_LTZ);

-- Monitoring: one row per pipeline run.
CREATE TABLE IF NOT EXISTS AUDIT.PIPELINE_RUNS (
  RUN_ID            VARCHAR NOT NULL PRIMARY KEY,
  STARTED_AT        TIMESTAMP_LTZ,
  FINISHED_AT       TIMESTAMP_LTZ,
  STATUS            VARCHAR,             -- RUNNING / SUCCESS / FAILED
  FILES_LOADED      NUMBER,
  ROWS_TO_SILVER    NUMBER,
  ROWS_QUARANTINED  NUMBER,
  ROWS_REJECTED     NUMBER,
  ROWS_WARNING      NUMBER,
  ERROR_MESSAGE     VARCHAR
);
