-- =====================================================================
-- 02_silver_ddl.sql
-- SILVER = validated, de-duplicated, correctly typed data.
--
-- Snowflake note: PRIMARY KEY / FOREIGN KEY / UNIQUE are *declared but
-- NOT enforced* - only NOT NULL is enforced and CHECK does not exist.
-- So uniqueness is guaranteed by the pipeline's MERGE and PROVEN by
-- tests/data_model. We still declare keys - they document the model and
-- BI tools use them.
-- =====================================================================

CREATE TABLE IF NOT EXISTS SILVER.MERCHANT (
  MERCHANT_ID       VARCHAR(20)  NOT NULL,
  MERCHANT_NAME     VARCHAR(200),
  MERCHANT_CATEGORY VARCHAR(100),
  COUNTRY           VARCHAR(60),
  RISK_LEVEL        VARCHAR(10)  NOT NULL,
  EFFECTIVE_FROM    DATE         NOT NULL,
  EFFECTIVE_TO      DATE,                       -- NULL = still active
  SOURCE_FILE       VARCHAR,
  LOADED_AT         TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_SILVER_MERCHANT PRIMARY KEY (MERCHANT_ID, EFFECTIVE_FROM)
);

CREATE TABLE IF NOT EXISTS SILVER.TRANSACTIONS (
  TRANSACTION_ID   VARCHAR(30)   NOT NULL,
  MERCHANT_ID      VARCHAR(20)   NOT NULL,
  CUSTOMER_ID      VARCHAR(30),
  TRANSACTION_TS   TIMESTAMP_NTZ NOT NULL,      -- business time
  AMOUNT           NUMBER(18,2)  NOT NULL,
  CURRENCY         VARCHAR(3)    NOT NULL,
  STATUS           VARCHAR(10)   NOT NULL,
  PAYMENT_CHANNEL  VARCHAR(10)   NOT NULL,
  SOURCE_FILE      VARCHAR,
  LOADED_AT        TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_SILVER_TRANSACTIONS PRIMARY KEY (TRANSACTION_ID)
);

CREATE TABLE IF NOT EXISTS SILVER.SETTLEMENTS (
  SETTLEMENT_ID      VARCHAR(30)   NOT NULL,
  TRANSACTION_ID     VARCHAR(30)   NOT NULL,
  SETTLEMENT_TS      TIMESTAMP_NTZ NOT NULL,
  SETTLEMENT_AMOUNT  NUMBER(18,2)  NOT NULL,
  SETTLEMENT_STATUS  VARCHAR(10)   NOT NULL,
  SETTLEMENT_BATCH   VARCHAR(30),
  SOURCE_FILE        VARCHAR,
  LOADED_AT          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_SILVER_SETTLEMENTS PRIMARY KEY (SETTLEMENT_ID),
  CONSTRAINT FK_SILVER_SETTLEMENT_TXN FOREIGN KEY (TRANSACTION_ID) REFERENCES SILVER.TRANSACTIONS (TRANSACTION_ID)
);

CREATE TABLE IF NOT EXISTS SILVER.PAYMENT_EVENTS (
  EVENT_ID             VARCHAR(30)   NOT NULL,
  TRANSACTION_ID       VARCHAR(30)   NOT NULL,
  EVENT_TYPE           VARCHAR(15)   NOT NULL,
  EVENT_TS             TIMESTAMP_NTZ NOT NULL,  -- business time (when it happened)
  INGESTION_TS         TIMESTAMP_NTZ NOT NULL,  -- processing time (when we received it)
  PROCESSING_MS        NUMBER,
  INGESTION_DELAY_SEC  NUMBER,
  IS_LATE              BOOLEAN       NOT NULL,
  SOURCE_FILE          VARCHAR,
  LOADED_AT            TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_SILVER_EVENTS PRIMARY KEY (EVENT_ID),
  CONSTRAINT FK_SILVER_EVENT_TXN FOREIGN KEY (TRANSACTION_ID) REFERENCES SILVER.TRANSACTIONS (TRANSACTION_ID)
);
