-- =====================================================================
-- 04_gold_transform.sql - SILVER -> GOLD, runs on every pipeline run.
-- Incremental: only Silver rows loaded after the Gold watermark are used,
-- and only the affected dates of the KPI table are recalculated.
-- MERGE = insert new rows / update changed rows, so re-running is safe.
-- =====================================================================

SET wm = (SELECT LAST_LOAD_TS FROM AUDIT.WATERMARK WHERE SOURCE = 'gold');
SET new_wm = (SELECT COALESCE(MAX(ts), $wm) FROM (
                SELECT MAX(LOADED_AT) AS ts FROM SILVER.MERCHANT
                UNION ALL SELECT MAX(LOADED_AT) FROM SILVER.TRANSACTIONS
                UNION ALL SELECT MAX(LOADED_AT) FROM SILVER.SETTLEMENTS
                UNION ALL SELECT MAX(LOADED_AT) FROM SILVER.PAYMENT_EVENTS));

-- 1. DIM_MERCHANT - SCD Type 2: one row per risk period (history comes from the source file)
MERGE INTO GOLD.DIM_MERCHANT d
USING (SELECT * FROM SILVER.MERCHANT WHERE LOADED_AT > $wm) s
ON d.MERCHANT_ID = s.MERCHANT_ID AND d.EFFECTIVE_FROM = s.EFFECTIVE_FROM
WHEN MATCHED THEN UPDATE SET
  d.MERCHANT_NAME = s.MERCHANT_NAME, d.RISK_LEVEL = s.RISK_LEVEL,
  d.EFFECTIVE_TO = COALESCE(s.EFFECTIVE_TO, '9999-12-31'::DATE)
WHEN NOT MATCHED THEN INSERT
  (MERCHANT_ID, MERCHANT_NAME, MERCHANT_CATEGORY, COUNTRY, RISK_LEVEL, EFFECTIVE_FROM, EFFECTIVE_TO, IS_CURRENT)
  VALUES (s.MERCHANT_ID, s.MERCHANT_NAME, s.MERCHANT_CATEGORY, s.COUNTRY, s.RISK_LEVEL,
          s.EFFECTIVE_FROM, COALESCE(s.EFFECTIVE_TO, '9999-12-31'::DATE), FALSE);

UPDATE GOLD.DIM_MERCHANT SET IS_CURRENT = (EFFECTIVE_TO = '9999-12-31'::DATE);

-- 2. DIM_CUSTOMER - only a hash of the customer id is stored (PII)
MERGE INTO GOLD.DIM_CUSTOMER d
USING (SELECT SHA2(CUSTOMER_ID) AS CUSTOMER_KEY, MIN(TRANSACTION_TS)::DATE AS FIRST_SEEN_DATE
       FROM SILVER.TRANSACTIONS WHERE LOADED_AT > $wm AND CUSTOMER_ID IS NOT NULL GROUP BY 1) s
ON d.CUSTOMER_KEY = s.CUSTOMER_KEY
WHEN NOT MATCHED THEN INSERT (CUSTOMER_KEY, FIRST_SEEN_DATE) VALUES (s.CUSTOMER_KEY, s.FIRST_SEEN_DATE);

-- 3. FACT_TRANSACTION - pick the merchant row whose risk period contains the transaction date
MERGE INTO GOLD.FACT_TRANSACTION f
USING (
  SELECT t.TRANSACTION_ID, TO_NUMBER(TO_CHAR(t.TRANSACTION_TS, 'YYYYMMDD')) AS DATE_KEY,
         m.MERCHANT_SK, t.MERCHANT_ID, SHA2(t.CUSTOMER_ID) AS CUSTOMER_KEY, t.TRANSACTION_TS,
         t.AMOUNT, t.CURRENCY, t.STATUS, t.PAYMENT_CHANNEL, m.RISK_LEVEL AS RISK_LEVEL_AT_TXN
  FROM SILVER.TRANSACTIONS t
  JOIN GOLD.DIM_MERCHANT m
    ON m.MERCHANT_ID = t.MERCHANT_ID
   AND t.TRANSACTION_TS::DATE BETWEEN m.EFFECTIVE_FROM AND m.EFFECTIVE_TO
  WHERE t.LOADED_AT > $wm
) s
ON f.TRANSACTION_ID = s.TRANSACTION_ID
WHEN MATCHED THEN UPDATE SET
  f.STATUS = s.STATUS, f.AMOUNT = s.AMOUNT, f.MERCHANT_SK = s.MERCHANT_SK,
  f.RISK_LEVEL_AT_TXN = s.RISK_LEVEL_AT_TXN, f.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (TRANSACTION_ID, DATE_KEY, MERCHANT_SK, MERCHANT_ID, CUSTOMER_KEY, TRANSACTION_TS, AMOUNT,
   CURRENCY, STATUS, PAYMENT_CHANNEL, RISK_LEVEL_AT_TXN)
  VALUES (s.TRANSACTION_ID, s.DATE_KEY, s.MERCHANT_SK, s.MERCHANT_ID, s.CUSTOMER_KEY, s.TRANSACTION_TS,
          s.AMOUNT, s.CURRENCY, s.STATUS, s.PAYMENT_CHANNEL, s.RISK_LEVEL_AT_TXN);

-- 4. FACT_SETTLEMENT - a settlement can change PENDING -> SETTLED, so matched rows are updated
MERGE INTO GOLD.FACT_SETTLEMENT f
USING (SELECT *, TO_NUMBER(TO_CHAR(SETTLEMENT_TS, 'YYYYMMDD')) AS DATE_KEY
       FROM SILVER.SETTLEMENTS WHERE LOADED_AT > $wm) s
ON f.SETTLEMENT_ID = s.SETTLEMENT_ID
WHEN MATCHED THEN UPDATE SET
  f.SETTLEMENT_TS = s.SETTLEMENT_TS, f.DATE_KEY = s.DATE_KEY, f.SETTLEMENT_AMOUNT = s.SETTLEMENT_AMOUNT,
  f.SETTLEMENT_STATUS = s.SETTLEMENT_STATUS, f.SETTLEMENT_BATCH = s.SETTLEMENT_BATCH,
  f.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (SETTLEMENT_ID, TRANSACTION_ID, DATE_KEY, SETTLEMENT_TS, SETTLEMENT_AMOUNT, SETTLEMENT_STATUS, SETTLEMENT_BATCH)
  VALUES (s.SETTLEMENT_ID, s.TRANSACTION_ID, s.DATE_KEY, s.SETTLEMENT_TS, s.SETTLEMENT_AMOUNT,
          s.SETTLEMENT_STATUS, s.SETTLEMENT_BATCH);

-- 5. FACT_PAYMENT_EVENT - events never change, so insert only
INSERT INTO GOLD.FACT_PAYMENT_EVENT
  (EVENT_ID, TRANSACTION_ID, DATE_KEY, EVENT_TYPE, EVENT_TS, INGESTION_TS, PROCESSING_MS, INGESTION_DELAY_SEC, IS_LATE)
SELECT EVENT_ID, TRANSACTION_ID, TO_NUMBER(TO_CHAR(EVENT_TS, 'YYYYMMDD')), EVENT_TYPE, EVENT_TS,
       INGESTION_TS, PROCESSING_MS, INGESTION_DELAY_SEC, IS_LATE
FROM SILVER.PAYMENT_EVENTS
WHERE LOADED_AT > $wm
  AND EVENT_ID NOT IN (SELECT EVENT_ID FROM GOLD.FACT_PAYMENT_EVENT);

-- Out-of-order events: number them by BUSINESS time (event_ts), not by arrival order
UPDATE GOLD.FACT_PAYMENT_EVENT f
SET EVENT_SEQ = x.SEQ
FROM (SELECT EVENT_ID, ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID ORDER BY EVENT_TS) AS SEQ
      FROM GOLD.FACT_PAYMENT_EVENT) x
WHERE f.EVENT_ID = x.EVENT_ID;

-- 6. KPI table - recalculate only the transaction dates that received new data
CREATE OR REPLACE TEMPORARY TABLE AUDIT.CHANGED_DATES AS
SELECT DISTINCT TRANSACTION_TS::DATE AS D FROM SILVER.TRANSACTIONS WHERE LOADED_AT > $wm
UNION
SELECT DISTINCT t.TRANSACTION_TS::DATE
FROM SILVER.SETTLEMENTS s JOIN SILVER.TRANSACTIONS t ON t.TRANSACTION_ID = s.TRANSACTION_ID
WHERE s.LOADED_AT > $wm;

DELETE FROM GOLD.AGG_MERCHANT_DAILY WHERE TXN_DATE IN (SELECT D FROM AUDIT.CHANGED_DATES);

INSERT INTO GOLD.AGG_MERCHANT_DAILY
SELECT TXN_DATE, MERCHANT_ID, MAX(MERCHANT_NAME), MAX(RISK_LEVEL),
       COUNT(*), SUM(AMOUNT), SUM(SETTLED_AMOUNT), SUM(SLA_MET)
FROM GOLD.V_TXN_SETTLEMENT
WHERE TXN_DATE IN (SELECT D FROM AUDIT.CHANGED_DATES)
GROUP BY TXN_DATE, MERCHANT_ID;

-- 7. Remember how far we got
UPDATE AUDIT.WATERMARK SET LAST_LOAD_TS = $new_wm WHERE SOURCE = 'gold';
