-- =====================================================================
-- 04_gold_transform.sql  - SILVER -> GOLD, run on every pipeline run.
-- INCREMENTAL: only Silver rows loaded after the last Gold watermark are
-- processed, and only the affected dates of the KPI table are rebuilt.
-- MERGE makes every step idempotent (safe to re-run).
-- =====================================================================

SET gold_wm = (SELECT LAST_LOAD_TS FROM AUDIT.WATERMARK WHERE LAYER = 'GOLD' AND SOURCE = 'ALL');
SET gold_hi = (SELECT COALESCE(MAX(ts), $gold_wm) FROM (
                 SELECT MAX(LOADED_AT) AS ts FROM SILVER.MERCHANT
                 UNION ALL SELECT MAX(LOADED_AT) FROM SILVER.TRANSACTIONS
                 UNION ALL SELECT MAX(LOADED_AT) FROM SILVER.SETTLEMENTS
                 UNION ALL SELECT MAX(LOADED_AT) FROM SILVER.PAYMENT_EVENTS));

-- 1. DIM_MERCHANT (SCD2): history rows come straight from the source.
MERGE INTO GOLD.DIM_MERCHANT d
USING (SELECT * FROM SILVER.MERCHANT WHERE LOADED_AT > $gold_wm) s
ON d.MERCHANT_ID = s.MERCHANT_ID AND d.EFFECTIVE_FROM = s.EFFECTIVE_FROM
WHEN MATCHED THEN UPDATE SET
  d.MERCHANT_NAME = s.MERCHANT_NAME, d.MERCHANT_CATEGORY = s.MERCHANT_CATEGORY, d.COUNTRY = s.COUNTRY,
  d.RISK_LEVEL = s.RISK_LEVEL, d.EFFECTIVE_TO = COALESCE(s.EFFECTIVE_TO, '9999-12-31'::DATE)
WHEN NOT MATCHED THEN INSERT
  (MERCHANT_ID, MERCHANT_NAME, MERCHANT_CATEGORY, COUNTRY, RISK_LEVEL, EFFECTIVE_FROM, EFFECTIVE_TO, IS_CURRENT)
  VALUES (s.MERCHANT_ID, s.MERCHANT_NAME, s.MERCHANT_CATEGORY, s.COUNTRY, s.RISK_LEVEL,
          s.EFFECTIVE_FROM, COALESCE(s.EFFECTIVE_TO, '9999-12-31'::DATE), FALSE);

-- The latest period of each merchant is the "current" row.
UPDATE GOLD.DIM_MERCHANT d
SET IS_CURRENT = (d.MERCHANT_SK = x.CURRENT_SK)
FROM (SELECT MERCHANT_ID, MAX_BY(MERCHANT_SK, EFFECTIVE_FROM) AS CURRENT_SK
      FROM GOLD.DIM_MERCHANT GROUP BY MERCHANT_ID) x
WHERE d.MERCHANT_ID = x.MERCHANT_ID;

-- 2. DIM_CUSTOMER: store only a hash of the customer id (PII minimisation).
MERGE INTO GOLD.DIM_CUSTOMER d
USING (SELECT SHA2(CUSTOMER_ID) AS CUSTOMER_KEY, MIN(TRANSACTION_TS)::DATE AS FIRST_SEEN_DATE
       FROM SILVER.TRANSACTIONS
       WHERE LOADED_AT > $gold_wm AND CUSTOMER_ID IS NOT NULL
       GROUP BY 1) s
ON d.CUSTOMER_KEY = s.CUSTOMER_KEY
WHEN NOT MATCHED THEN INSERT (CUSTOMER_KEY, FIRST_SEEN_DATE) VALUES (s.CUSTOMER_KEY, s.FIRST_SEEN_DATE);

-- 3. FACT_TRANSACTION with POINT-IN-TIME risk: join the merchant row whose
--    effective range contains the transaction date (Issue 4).
--    Also re-processes transactions of merchants whose risk history changed.
MERGE INTO GOLD.FACT_TRANSACTION f
USING (
  SELECT t.TRANSACTION_ID,
         TO_NUMBER(TO_CHAR(t.TRANSACTION_TS, 'YYYYMMDD')) AS DATE_KEY,
         m.MERCHANT_SK, t.MERCHANT_ID,
         SHA2(t.CUSTOMER_ID) AS CUSTOMER_KEY,
         t.TRANSACTION_TS, t.AMOUNT, t.CURRENCY, t.STATUS, t.PAYMENT_CHANNEL,
         m.RISK_LEVEL AS RISK_LEVEL_AT_TXN
  FROM SILVER.TRANSACTIONS t
  JOIN GOLD.DIM_MERCHANT m
    ON m.MERCHANT_ID = t.MERCHANT_ID
   AND t.TRANSACTION_TS::DATE BETWEEN m.EFFECTIVE_FROM AND m.EFFECTIVE_TO
  WHERE t.LOADED_AT > $gold_wm
     OR t.MERCHANT_ID IN (SELECT MERCHANT_ID FROM SILVER.MERCHANT WHERE LOADED_AT > $gold_wm)
  QUALIFY ROW_NUMBER() OVER (PARTITION BY t.TRANSACTION_ID ORDER BY m.EFFECTIVE_FROM DESC) = 1
) s
ON f.TRANSACTION_ID = s.TRANSACTION_ID
WHEN MATCHED THEN UPDATE SET
  f.DATE_KEY = s.DATE_KEY, f.MERCHANT_SK = s.MERCHANT_SK, f.MERCHANT_ID = s.MERCHANT_ID,
  f.CUSTOMER_KEY = s.CUSTOMER_KEY, f.TRANSACTION_TS = s.TRANSACTION_TS, f.AMOUNT = s.AMOUNT,
  f.CURRENCY = s.CURRENCY, f.STATUS = s.STATUS, f.PAYMENT_CHANNEL = s.PAYMENT_CHANNEL,
  f.RISK_LEVEL_AT_TXN = s.RISK_LEVEL_AT_TXN, f.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (TRANSACTION_ID, DATE_KEY, MERCHANT_SK, MERCHANT_ID, CUSTOMER_KEY, TRANSACTION_TS, AMOUNT,
   CURRENCY, STATUS, PAYMENT_CHANNEL, RISK_LEVEL_AT_TXN)
  VALUES (s.TRANSACTION_ID, s.DATE_KEY, s.MERCHANT_SK, s.MERCHANT_ID, s.CUSTOMER_KEY, s.TRANSACTION_TS,
          s.AMOUNT, s.CURRENCY, s.STATUS, s.PAYMENT_CHANNEL, s.RISK_LEVEL_AT_TXN);

-- 4. FACT_SETTLEMENT (a settlement can change PENDING -> SETTLED, so MERGE updates it).
MERGE INTO GOLD.FACT_SETTLEMENT f
USING (SELECT SETTLEMENT_ID, TRANSACTION_ID, TO_NUMBER(TO_CHAR(SETTLEMENT_TS, 'YYYYMMDD')) AS DATE_KEY,
              SETTLEMENT_TS, SETTLEMENT_AMOUNT, SETTLEMENT_STATUS, SETTLEMENT_BATCH
       FROM SILVER.SETTLEMENTS WHERE LOADED_AT > $gold_wm) s
ON f.SETTLEMENT_ID = s.SETTLEMENT_ID
WHEN MATCHED THEN UPDATE SET
  f.TRANSACTION_ID = s.TRANSACTION_ID, f.DATE_KEY = s.DATE_KEY, f.SETTLEMENT_TS = s.SETTLEMENT_TS,
  f.SETTLEMENT_AMOUNT = s.SETTLEMENT_AMOUNT, f.SETTLEMENT_STATUS = s.SETTLEMENT_STATUS,
  f.SETTLEMENT_BATCH = s.SETTLEMENT_BATCH, f.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (SETTLEMENT_ID, TRANSACTION_ID, DATE_KEY, SETTLEMENT_TS, SETTLEMENT_AMOUNT, SETTLEMENT_STATUS, SETTLEMENT_BATCH)
  VALUES (s.SETTLEMENT_ID, s.TRANSACTION_ID, s.DATE_KEY, s.SETTLEMENT_TS, s.SETTLEMENT_AMOUNT,
          s.SETTLEMENT_STATUS, s.SETTLEMENT_BATCH);

-- 5. FACT_PAYMENT_EVENT (events never change -> insert only).
MERGE INTO GOLD.FACT_PAYMENT_EVENT f
USING (SELECT EVENT_ID, TRANSACTION_ID, TO_NUMBER(TO_CHAR(EVENT_TS, 'YYYYMMDD')) AS DATE_KEY, EVENT_TYPE,
              EVENT_TS, INGESTION_TS, PROCESSING_MS, INGESTION_DELAY_SEC, IS_LATE
       FROM SILVER.PAYMENT_EVENTS WHERE LOADED_AT > $gold_wm) s
ON f.EVENT_ID = s.EVENT_ID
WHEN NOT MATCHED THEN INSERT
  (EVENT_ID, TRANSACTION_ID, DATE_KEY, EVENT_TYPE, EVENT_TS, INGESTION_TS, PROCESSING_MS, INGESTION_DELAY_SEC, IS_LATE)
  VALUES (s.EVENT_ID, s.TRANSACTION_ID, s.DATE_KEY, s.EVENT_TYPE, s.EVENT_TS, s.INGESTION_TS,
          s.PROCESSING_MS, s.INGESTION_DELAY_SEC, s.IS_LATE);

-- Out-of-order events (Issue 3): number them by BUSINESS time, not arrival.
UPDATE GOLD.FACT_PAYMENT_EVENT f
SET EVENT_SEQ = x.SEQ
FROM (SELECT EVENT_ID,
             ROW_NUMBER() OVER (PARTITION BY TRANSACTION_ID ORDER BY EVENT_TS, EVENT_ID) AS SEQ
      FROM GOLD.FACT_PAYMENT_EVENT
      WHERE TRANSACTION_ID IN (SELECT TRANSACTION_ID FROM SILVER.PAYMENT_EVENTS WHERE LOADED_AT > $gold_wm)) x
WHERE f.EVENT_ID = x.EVENT_ID;

-- 6. KPI table: rebuild only the transaction dates touched by this run.
CREATE OR REPLACE TEMPORARY TABLE AUDIT.AFFECTED_DATES AS
SELECT DISTINCT TRANSACTION_TS::DATE AS D FROM SILVER.TRANSACTIONS WHERE LOADED_AT > $gold_wm
UNION
SELECT DISTINCT t.TRANSACTION_TS::DATE
FROM SILVER.SETTLEMENTS s JOIN SILVER.TRANSACTIONS t ON t.TRANSACTION_ID = s.TRANSACTION_ID
WHERE s.LOADED_AT > $gold_wm
UNION
SELECT DISTINCT TRANSACTION_TS::DATE FROM SILVER.TRANSACTIONS
WHERE MERCHANT_ID IN (SELECT MERCHANT_ID FROM SILVER.MERCHANT WHERE LOADED_AT > $gold_wm);

BEGIN;

DELETE FROM GOLD.AGG_MERCHANT_DAILY WHERE TXN_DATE IN (SELECT D FROM AUDIT.AFFECTED_DATES);

INSERT INTO GOLD.AGG_MERCHANT_DAILY
SELECT TXN_DATE,
       TO_NUMBER(TO_CHAR(TXN_DATE, 'YYYYMMDD')),
       MERCHANT_ID,
       MAX(MERCHANT_NAME),
       MAX(RISK_LEVEL),
       COUNT(*),
       COUNT_IF(STATUS = 'SUCCESS'),
       COUNT_IF(STATUS = 'FAILED'),
       COUNT_IF(STATUS = 'REVERSED'),
       SUM(IFF(STATUS = 'SUCCESS', AMOUNT, 0)),
       SUM(IFF(STATUS = 'SUCCESS', SETTLED_AMOUNT, 0)),
       SUM(SLA_MET),
       COUNT_IF(SETTLEMENT_CLASS = 'SETTLED'),
       COUNT_IF(SETTLEMENT_CLASS = 'PARTIALLY_SETTLED'),
       COUNT_IF(SETTLEMENT_CLASS = 'PENDING'),
       COUNT_IF(SETTLEMENT_CLASS = 'SETTLEMENT_FAILED'),
       COUNT_IF(SETTLEMENT_CLASS = 'UNSETTLED'),
       SUM(IFF(SETTLEMENT_CLASS = 'PARTIALLY_SETTLED', GAP_AMOUNT, 0)),
       SUM(IFF(SETTLEMENT_CLASS = 'PENDING',           GAP_AMOUNT, 0)),
       SUM(IFF(SETTLEMENT_CLASS = 'SETTLEMENT_FAILED', GAP_AMOUNT, 0)),
       SUM(IFF(SETTLEMENT_CLASS = 'UNSETTLED',         GAP_AMOUNT, 0)),
       CURRENT_TIMESTAMP()
FROM GOLD.V_TXN_SETTLEMENT
WHERE TXN_DATE IN (SELECT D FROM AUDIT.AFFECTED_DATES)
GROUP BY TXN_DATE, MERCHANT_ID;

-- 7. Move the Gold watermark forward.
UPDATE AUDIT.WATERMARK
SET LAST_LOAD_TS = $gold_hi, UPDATED_AT = CURRENT_TIMESTAMP()
WHERE LAYER = 'GOLD' AND SOURCE = 'ALL';

COMMIT;
