-- =====================================================================
-- 99_reset.sql - start again from zero (keeps tables, deletes data).
-- Run in Snowsight as SYSADMIN, then: python -m pipeline.run_pipeline
-- (to redo the incremental demo, first delete dataaw\*_002.csv)
-- =====================================================================
USE DATABASE SETTLEMENT_DB;
USE WAREHOUSE SETTLE_WH;

REMOVE @BRONZE.RAW_STAGE;

TRUNCATE TABLE BRONZE.MERCHANT;
TRUNCATE TABLE BRONZE.TRANSACTIONS;
TRUNCATE TABLE BRONZE.SETTLEMENTS;
TRUNCATE TABLE BRONZE.PAYMENT_EVENTS;

TRUNCATE TABLE SILVER.MERCHANT;
TRUNCATE TABLE SILVER.TRANSACTIONS;
TRUNCATE TABLE SILVER.SETTLEMENTS;
TRUNCATE TABLE SILVER.PAYMENT_EVENTS;

TRUNCATE TABLE GOLD.DIM_MERCHANT;
TRUNCATE TABLE GOLD.DIM_CUSTOMER;
TRUNCATE TABLE GOLD.FACT_TRANSACTION;
TRUNCATE TABLE GOLD.FACT_SETTLEMENT;
TRUNCATE TABLE GOLD.FACT_PAYMENT_EVENT;
TRUNCATE TABLE GOLD.AGG_MERCHANT_DAILY;

TRUNCATE TABLE AUDIT.DQ_LOG;
TRUNCATE TABLE AUDIT.PIPELINE_RUNS;
UPDATE AUDIT.WATERMARK SET LAST_LOAD_TS = '1970-01-01 00:00:00'::TIMESTAMP_LTZ;
